### ISSUE TITLE
Ok i'm excited about this 😁

### ISSUE THREAD

**Issue by alob-mtc** [opensaucerer/saucelang#1]
Just an idea, what if this was completely build with an open culture. the community decide on the features to have.

Also the full specs of the language and expectations as drafted in some form of RFC then we split out the rfc into component of the language.

mini-roadmap 
- language expectations and specification 
- syntax design 
- language implementation  

what do you think?

**Comment by opensaucerer** [comment]
RFC - BIP - SIP ......nice! 

for the roadmap...I'm yet to work on the expectation and specifications but what I know for sure is that I plan to write the interpreter in Golang....saucelang will be interpreted. 

Essentially, the simplicity JS provides beginners is what inspired saucelang but design, of course, won't entirely follow after JS.

**Comment by alob-mtc** [comment]
Dope
